### ISSUE TITLE
validation problem on requests with query parameter of array type

### ISSUE THREAD

**Issue by guybedo** [krakenjs/swaggerize-hapi#25]
the swagger spec allows definition of query parameters of type array but queries generated using swagger-ui are not accepted by swaggerize-hapi.

For example, i have this definition for a get request : 
```
get:
      parameters:
        - name: fields
          in: query
          required: false
          type: array
          items:
            type: string
          enum: [date, title, description]
        
```
The server accepts requests with the "fields" parameter encoded in these formats:
fields[]=date,title,description
fields=date&fields=title&fields=description

BUT swagger-ui generates this kind of request : http://test.api.com/request?fields=date,title,description
This request is not accepted by the server and i have a 400 response :'fields must be an array'

So it seems that the implementation does not respect the swagger spec
